declare module "@tabler/icons-react" {
  import * as React from "react";
  export const IconCamera: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconChartBar: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconDashboard: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconDatabase: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconFileAi: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconFileDescription: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconFileWord: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconFolder: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconHelp: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconInnerShadowTop: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconListDetails: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconReport: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconSearch: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconSettings: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconUsers: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconChevronDown: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconChevronLeft: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconChevronRight: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconChevronsLeft: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconChevronsRight: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconCircleCheckFilled: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconDotsVertical: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconGripVertical: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconLayoutColumns: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconLoader: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconPlus: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconTrendingUp: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconDots: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconShare3: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconTrash: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconCirclePlusFilled: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconMail: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconCreditCard: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconLogout: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconNotification: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconUserCircle: React.FC<React.SVGProps<SVGSVGElement>>;
  export const IconTrendingDown: React.FC<React.SVGProps<SVGSVGElement>>;
  const Icon: React.FC<React.SVGProps<SVGSVGElement>>;
  export default Icon;
  export type Icon = React.FC<React.SVGProps<SVGSVGElement>>;
}
